describe("Assignment 1: Testing", () => {
  it("tests Assignment 1: Testing", () => {
    cy.viewport(700, 764);
    cy.visit("https://assignment-1-portfolio-site.onrender.com/signup");
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("ifeanyi");
    cy.get("label:nth-of-type(2) > input").type("njoku");
    cy.get("label:nth-of-type(3) > input").type("ifeanyi@example.com");
    cy.get("label:nth-of-type(4) > input").type("password");
    cy.get("button").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("ifeanyi@example.com");
    cy.get("label:nth-of-type(2) > input").type("password");
    cy.get("button").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("div > button").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("Re");
    cy.get("label:nth-of-type(1) > input").type("Realtor W");
    cy.get("label:nth-of-type(1) > input").type("Realtor Webpage");
    cy.get("textarea").type("C");
    cy.get("textarea").type("Created a realtor webpage that showed different houses and condos for sale");
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").type("2021-07-15");
    cy.get("#root > div button").click();
    cy.get("nav > button").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("ifeanyi@example.com");
    cy.get("label:nth-of-type(2) > input").click();
    cy.get("label:nth-of-type(2) > input").type("password");
    cy.get("button").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("#root > div > div button:nth-of-type(1)").click();
    cy.get("textarea").click();
    cy.get("textarea").type("Created a realtor webpage that showed different houses and condos for sale. It also had graphs that compared housing prices.");
    cy.get("#root > div button").click();
    cy.get("nav > button").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("ifeanyi@example.com");
    cy.get("label:nth-of-type(2) > input").click();
    cy.get("label:nth-of-type(2) > input").type("password");
    cy.get("form").click();
    cy.get("button").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("button:nth-of-type(2)").click();
    cy.get("nav > button").click();
  });
});
